Repository coala/coala-bears, pull requests merged in 2018-08, with the labels that each got.

#2613 LineLengthBear: Migrate to aspects
  bears/general/LineLengthBear.py
  tests/general/LineLengthBearTest.py
Labels: size/XS

#2615 setup.cfg: Remove pytest config 'python_functions'
  setup.cfg
  tests/documentation/DocGrammarBearTest.py
  tests/documentation/DocumentationStyleBearTest.py
  tests/python/BanditBearTest.py
Labels: size/XS

#2655 ClangBear.py: Rename variable range
  bears/c_languages/ClangBear.py
Labels: difficulty/newcomer, needs rebase, size/XS, type/codestyle

#2641 bear-requirements.txt: Bump pyflakes
  bear-requirements.txt
  bear-requirements.yaml
  bears/python/PyFlakesBear.py
Labels: size/XS, status/blocked

#2657 PycodestyleBear: Migrate bear to aspects
  bears/python/PycodestyleBear.py
  tests/python/PycodestyleBearTest.py
Labels: area/aspects, size/XS

#2648 generate_package.py: Remove from coala-bears
  .ci/generate_package.py
  .coafile
  .moban.dt/bears-test-requirements.txt.jj2
  .moban.dt/setup.py.in
  bears/requirements.txt
  setup.cfg
  test-requirements.txt
  tests/generate_packageTest.py
Labels: difficulty/medium, importance/medium, process/pending review, size/XS

#2663 .coafile: Set max line characters to 80
  .coafile
Labels: process/pending review, size/XS, type/codestyle

#2661 Sync templates
  .ci/appveyor.yml
  setup.py
  test-requirements.txt
Labels: process/pending review, size/S

#2523 CISkipInspectBear.py: Bear to inspect commits that disable CI builds
  bears/vcs/git/CISkipInspectBear.py
  tests/vcs/git/CISkipInspectBearTest.py
Labels: bear proposal, difficulty/medium, process/pending review, size/S

#2268 BashateBear.py: Add a new lint bear
  .ci/check_unsupported.sh
  bear-requirements.txt
  bear-requirements.yaml
  bears/shell/BashateBear.py
  tests/shell/BashateBearTest.py
Labels: area/lintbears, bear proposal, difficulty/low, process/pending review, size/S

#2242 GherkinLintBear.py: Add new lint bear
  bear-requirements.yaml
  bears/gherkin/GherkinLintBear.py
  bears/gherkin/__init__.py
  package.json
  tests/gherkin/GherkinLintBearTest.py
  tests/gherkin/__init__.py
  tests/gherkin/config_files/.gherkin-lintrc
  tests/gherkin/test_files/.gherkin-lintrc
  tests/gherkin/test_files/DuplicateFeatureName-Pt1.feature
  tests/gherkin/test_files/DuplicateFeatureName-Pt2.feature
  tests/gherkin/test_files1/DuplicateFeatureName-Pt1.feature
  tests/gherkin/test_files1/DuplicateFeatureName-Pt2.feature
  tests/gherkin/test_files1/DuplicateScenarioName.feature
  tests/gherkin/test_files1/DuplicateTags.feature
  tests/gherkin/test_files1/EmptyFeature.feature
  tests/gherkin/test_files1/MultipleEmptyLines.feature
  tests/gherkin/test_files1/NoHomogenousTags.feature
  tests/gherkin/test_files1/NoNewLineAtEOF.feature
  tests/gherkin/test_files1/NoRestrictedTags.feature
  tests/gherkin/test_files1/NoScenarios.feature
  tests/gherkin/test_files1/NoSuperfluousTags.feature
  tests/gherkin/test_files1/OnlyScenarioOutlines.feature
  tests/gherkin/test_files1/PartiallyCommentedTagLine.feature
  tests/gherkin/test_files1/ScenarioOutlineWithoutExamples.feature
  tests/gherkin/test_files1/TrailingSpaces.feature
  tests/gherkin/test_files1/TrailingTab.feature
  tests/gherkin/test_files1/UnnamedFeature.feature
  tests/gherkin/test_files1/UnnamedScenario.feature
  tests/gherkin/test_files1/UseAnd.feature
  tests/gherkin/test_files2/MultipleBackgrounds.feature
  tests/gherkin/test_files2/MultipleFeatures.feature
  tests/gherkin/test_files2/TagOnBackground.feature
Labels: area/lintbears, bear proposal, difficulty/low, process/pending review, size/L

#2230 ESLintBear.py: Add settings from eslint
  bear-requirements.yaml
  bears/js/ESLintBear.py
  package.json
  tests/js/ESLintBearTest.py
Labels: area/ci, area/lintbears, area/newsettings, difficulty/low, process/pending review, size/S

#2652 GitRevertInspectBear.py: New bear
  bears/vcs/git/GitRevertInspectBear.py
  tests/vcs/git/GitRevertInspectBearTest.py
Labels: process/pending review, size/M

#2667 Jinja2Bear: Disable the need of trailing comment
  bears/jinja2/Jinja2Bear.py
  tests/jinja2/Jinja2BearTest.py
Labels: difficulty/low, importance/medium, process/pending review, size/XS

#2675 GNUIndentBear.py: Fix max_line_length=0
  bears/c_languages/GNUIndentBear.py
Labels: difficulty/low, importance/low, process/pending review, size/XS, type/bug

#2679 BanditBearTest.py: Support bandit 1.5
  tests/python/BanditBearTest.py
Labels: area/tests, difficulty/low, importance/critical, process/pending review, size/XS, type/test
