Repository coala/coala-bears, pull requests merged in 2018-11, with the labels that each got.

#2749 Add asciinema video to BanditBear
  bears/python/BanditBear.py
Labels: size/XS

#2752 Add asciinema video to RubyFastererBear
  bears/ruby/RubyFastererBear.py
Labels: size/XS

#2750 JSONFormatBear.py: Implement max_line_length
  bears/js/JSONFormatBear.py
  tests/js/JSONFormatBearTest.py
Labels: area/nativebear, difficulty/low, importance/low, size/XS, type/feature

#2755 CommitBear.py: Check proper use of `https` when referencing issues
  bears/vcs/CommitBear.py
  tests/vcs/git/GitCommitBearTest.py
  tests/vcs/mercurial/HgCommitBearTest.py
Labels: area/ci, difficulty/low, difficulty/newcomer, importance/low, initiatives/gci, size/XS, status/needs info

#2759 LineContinuationBear.py: Add line continuation bear
  bear-languages.yaml
  bears/general/LineContinuationBear.py
  tests/general/LineContinuationBearTest.py
Labels: area/genericbears, bear proposal, difficulty/low, importance/high, initiatives/gci, size/S

#2764 PyStringConcatBear.py: Add Py string concat bear
  bear-languages.yaml
  bears/python/PyStringConcatBear.py
  tests/python/PyStringConcatBearTest.py
Labels: bear proposal, difficulty/medium, initiatives/gci, size/S

#2778 TextLintBearTest: Remove unnecessary result
  tests/general/TextLintBearTest.py
  tests/general/textlint_test_files/bad_alex_no_dead_link.md
Labels: difficulty/low, importance/high, process/pending review, size/XS, type/dependencies

#2781 SQLFormatBear.py: Add sqlparse bear
  bear-languages.yaml
  bear-requirements.txt
  bear-requirements.yaml
  bears/sql/SQLFormatBear.py
  tests/sql/SQLFormatBearTest.py
Labels: bear proposal, difficulty/low, importance/medium, initiatives/gci, size/S

#2785 Adds asciinema to MatLab Bear
  bears/matlab/MatlabIndentationBear.py
Labels: difficulty/newcomer, initiatives/gci, size/XS

#2786 HTTPSBear: Remove use of generic no cover
  bears/general/HTTPSBear.py
  tests/general/HTTPSBearTest.py
Labels: difficulty/low, initiatives/gci, process/pending review, size/XS

#2791 DocGrammarBear: Remove use of generic no cover
  bears/documentation/DocGrammarBear.py
  tests/documentation/DocGrammarBearTest.py
Labels: difficulty/medium, initiatives/gci, process/pending review, size/XS
