Repository coala/coala-bears, pull requests merged in 2018-12, with the labels that each got.

#2797 Fix CommitBear coverage drop
  bears/vcs/CommitBear.py
Labels: difficulty/low, importance/critical, initiatives/gci, size/XS, type/bug

#2801 GitRevertInspectBear: Remove use of no cover
  bears/vcs/git/GitRevertInspectBear.py
  tests/vcs/git/GitRevertInspectBearTest.py
Labels: difficulty/low, initiatives/gci, size/XS

#2792 CPDBear: Remove use of generic no cover
  bears/general/CPDBear.py
  tests/general/CPDBearTest.py
Labels: difficulty/low, initiatives/gci, size/XS

#2776 PySafetyBear: Remove use of generic no cover
  bears/python/requirements/PySafetyBear.py
  tests/python/requirements/PySafetyBearTest.py
Labels: difficulty/low, initiatives/gci, size/XS

#2787 PyImportSortBear.py: Adds asciinema
  bears/python/PyImportSortBear.py
Labels: difficulty/newcomer, initiatives/gci, size/XS

#2795 LanguageToolBear: Remove use of generic no cover
  bears/natural_language/LanguageToolBear.py
  tests/natural_language/LanguageToolBearTest.py
Labels: difficulty/low, initiatives/gci, process/pending review, size/XS

#2794 VHDLLintBear: Remove use of generic no cover
  bears/vhdl/VHDLLintBear.py
  tests/vhdl/VHDLLintBearTest.py
Labels: difficulty/low, initiatives/gci, process/pending review, size/XS

#2809 JavaPMDBear: Remove use of generic no cover
  bears/java/JavaPMDBear.py
  tests/java/JavaPMDBearTest.py
Labels: difficulty/low, initiatives/gci, size/XS

#2804 ESLintBear: Remove use of generic no cover
  bears/js/ESLintBear.py
  tests/js/ESLintBearTest.py
Labels: difficulty/low, difficulty/medium, importance/medium, initiatives/gci, long-term-project, size/XS, type/test

#1312 Install Ruby gems in AppVeyor
  .ci/appveyor.yml
  bears/configfiles/PuppetLintBear.py
  bears/haml/HAMLLintBear.py
  bears/ruby/RubySecurityBear.py
  bears/ruby/RubySmellBear.py
  bears/scss/SCSSLintBear.py
  bears/yaml/TravisLintBear.py
Labels: difficulty/low, importance/medium, process/pending review, review carefully!, size/XS

#2817 .ci/appveyor.yml: Use Ruby 2.4
  .ci/appveyor.yml
Labels: process/pending review, size/XS
