Repository coala/coala-bears, pull requests merged in 2018-10, with the labels that each got.

#2691 ApertiumLintBear.py: Remove line break
  bears/apertium/ApertiumLintBear.py
Labels: area/documentation, difficulty/newcomer, in progress, size/XS

#2709 Sync with new moban
  .ci/check_unsupported.sh
  setup.py
  test-requirements.txt
Labels: size/XS

#2696 Add composer requirement
  .ci/generate_bear_requirements.py
  bear-requirements.yaml
  bears/php/PHPCodeSnifferBear.py
  bears/php/PHPMessDetectorBear.py
  tests/general/textlint_test_files/bad_ginger.rst
Labels: difficulty/low, importance/low, size/XS

#2705 PEP8NotebookBear.py: Spell mistake fix
  bears/python/PEP8NotebookBear.py
Labels: area/documentation, difficulty/newcomer, size/XS, type/bug

#2713 YAMLLintBear: Update version to 1.12.0
  bear-requirements.txt
  bear-requirements.yaml
  bears/yaml/YAMLLintBear.py
Labels: size/XS, type/dependencies

#2701 PEP8Bear.py: Change the docstring Indentation
  bears/python/PEP8Bear.py
Labels: area/documentation, difficulty/newcomer, in progress, size/XS

#2720 IndentationBear.py: Fix docstring typo
  bears/general/IndentationBear.py
Labels: difficulty/newcomer, size/XS

#2728 Change C++ to CPP at bears language
  bears/c_languages/ArtisticStyleBear.py
  bears/c_languages/CPPCheckBear.py
  bears/c_languages/CPPCleanBear.py
  bears/c_languages/CPPLintBear.py
  bears/c_languages/CSecurityBear.py
  bears/c_languages/ClangBear.py
  bears/c_languages/GNUIndentBear.py
Labels: area/documentation, difficulty/newcomer, size/XS

#2731 add generating requirements for R bots
  .ci/generate_bear_requirements.py
  .moban.dt/DESCRIPTION.jj2
  .moban.yaml
  bear-requirements.yaml
  bears/r/FormatRBear.py
  bears/r/RLintBear.py
Labels: difficulty/low, importance/low, initiatives/gci, size/XS

#2742 PEP8NotebookBear: Add infinite length feature
  bears/python/PEP8NotebookBear.py
  tests/python/PEP8NotebookBearTest.py
Labels: area/ci, difficulty/low, importance/low, in progress, size/XS

#2154 PythonPackageInitBear.py: Create Asciinema
  bears/python/PythonPackageInitBear.py
Labels: difficulty/newcomer, hacktoberfest, size/XS
