Repository coala/coala-bears, pull requests merged in 2018-07, with the labels that each got.

#2501 GitCommitBear: Ignore Github PR merge commits
  .travis.yml
  bears/vcs/git/GitCommitBear.py
  tests/vcs/git/GitCommitBearTest.py
Labels: area/newsettings, difficulty/high, importance/medium, process/pending review, size/S

#2576 generate_package.py: Replace touch
  bears/generate_package.py
  tests/generate_packageTest.py
Labels: difficulty/low, importance/low, size/XS

#2580 FilenameBear: Don't make diff if changes are same
  bears/general/FilenameBear.py
Labels: difficulty/low, importance/medium, size/XS, type/bug

#2577 InvalidLinkBearTest: Fix test_redirect_threshold
  tests/general/InvalidLinkBearTest.py
Labels: difficulty/low, importance/critical, size/XS, type/bug

#2581 FilenameBearTest: Fix testcases
  tests/general/FilenameBearTest.py
Labels: difficulty/low, importance/critical, size/XS, type/bug

#2587 ClangComplexityBear: Fix SourceRange AttributeError
  bears/c_languages/ClangComplexityBear.py
Labels: difficulty/low, importance/critical, size/XS, type/bug

#2541 .travis.yml: Add sentinel job
  .travis.yml
Labels: size/XS

#2568 appveyor.yml: Sync moban
  .ci/appveyor.yml
  .moban.yaml
Labels: size/XS, type/bug

#2593 CI: Use cs50/ppa for astyle 3.0.1
  .ci/deps.apt.sh
  .ci/deps.sh
  .travis.yml
Labels: area/ci, difficulty/low, size/XS, type/dependencies, upstream

#2606 TextLintBearTest: Replace httpstat.us with Google
  tests/general/TextLintBearTest.py
  tests/general/textlint_test_files/bad_alex_no_dead_link.md
Labels: area/tests, difficulty/low, importance/critical, size/XS, type/dependencies

#2446 .ci/generate_bear_requirements: Changes
  .ci/generate_bear_requirements.py
  .moban.dt/bears-test-requirements.txt.jj2
  .moban.yaml
  .travis.yml
  bear-requirements.yaml
  test-requirements.txt
Labels: area/ci, difficulty/medium, importance/medium, size/S

#2599 .ci/deps.sh: Remove go deps now in .ci/deps.go.sh
  .ci/deps.sh
Labels: area/ci, difficulty/low, importance/critical, process/pending review, size/XS, type/bug

#2626 PySafetyBear: Update PySafetyBear
  bear-requirements.txt
  bear-requirements.yaml
  bears/python/requirements/PySafetyBear.py
  tests/python/requirements/PySafetyBearTest.py
  tests/python/requirements/PySafetyBearWithoutMockTest.py
Labels: size/S

#2630 PySafetyBear.py: Fix comment typo
  bears/python/requirements/PySafetyBear.py
Labels: difficulty/newcomer, size/XS, type/spelling

#2605 CPDBear: Update URL
  bears/general/CPDBear.py
Labels: area/documentation, difficulty/newcomer, size/XS

#2639 bears/Constants.py : Adds VERSION to all
  bears/Constants.py
Labels: difficulty/newcomer, size/XS

#2595 RubyFastererBear.py: Add `fasterer`
  Gemfile
  bear-requirements.yaml
  bears/ruby/RubyFastererBear.py
  tests/ruby/RubyFastererBearTest.py
  tests/ruby/fasterer_test_files/module_eval.rb
  tests/ruby/fasterer_test_files/sort_vs_sort_by.rb
Labels: area/lintbears, size/S

#2543 VCSCommitMetadataBear: New meta bear for analyzing commits
  bears/vcs/VCSCommitMetadataBear.py
  bears/vcs/git/GitCommitMetadataBear.py
  tests/vcs/VCSCommitMetadataBearTest.py
  tests/vcs/git/GitCommitMetadataBearTest.py
Labels: area/documentation, area/lintbears, difficulty/newcomer, size/M, type/spelling, type/test

#2649 MypyBear: Upgrade mypy
  .ci/check_unsupported.sh
  bear-requirements.txt
  bear-requirements.yaml
  bears/python/MypyBear.py
Labels: area/ci, difficulty/low, importance/high, size/XS, type/dependencies
