Repository coala/coala-bears, pull requests merged in 2018-09, with the labels that each got.

#2680 JuliaLintBearTest: Remove timeout
  tests/julia/JuliaLintBearTest.py
Labels: area/tests, difficulty/low, importance/critical, process/pending review, size/XS, type/test

#2686 .travis.yml: Remove Python 3.6
  .travis.yml
Labels: size/XS

#2684 TailorBearTest.py & TSLintBearTest.py : Change test variables name
  tests/swift/TailorBearTest.py
  tests/typescript/TSLintBearTest.py
Labels: difficulty/newcomer, importance/low, process/pending review, size/XS

#2690 .travis.yml : removed CIRCLE_NODE_INDEX=-1
  .travis.yml
Labels: area/ci, difficulty/newcomer, importance/low, in progress, size/XS
