Repository coala/coala-bears, pull requests merged in 2018-03, with the labels that each got.

#2325 .ci/deps.sh: Display version of npm deps
  .ci/deps.sh
Labels: size/XS

#2253 Jinja2Bear: Add support for whitespace control
  bears/jinja2/Jinja2Bear.py
  tests/jinja2/Jinja2BearTest.py
Labels: size/S

#2284 LanguageToolBear: Use triple double quotes
  bears/natural_language/LanguageToolBear.py
Labels: size/XS

#2281 PEP8Bear.py: Add asciinema
  bears/python/PEP8Bear.py
Labels: size/XS

#1949 LogPrinter: Replace LogPrinter with logging
  .ci/generate_bear_requirements.py
Labels: size/XS, status/STALE

#2263 PycodestyleBearTest.py: Rename last LineLength test
  tests/python/PycodestyleBearTest.py
Labels: size/XS

#2269 PycodeStyleBear:Allow infinite line length
  bears/python/PycodestyleBear.py
  tests/python/PycodestyleBearTest.py
Labels: size/XS

#2292 DockerfileLintBear.py: Add SEE_MORE attribute
  bears/configfiles/DockerfileLintBear.py
Labels: process/pending review, size/XS

#2360 CI Deps: Pip version pin to 9.0.1
  .ci/deps.pip.sh
  test-requirements.txt
Labels: process/pending review, size/XS, type/bug

#2363 .travis.yml: Skip unsupported except on master
  .travis.yml
Labels: process/pending review, size/XS

#2362 .ci/check_unsupported.sh: Pin pytest-runner
  .ci/check_unsupported.sh
Labels: process/pending review, size/XS, type/bug

#2278 CoffeeLintBear: Add 0 max_line_length test
  tests/coffee_script/CoffeeLintBearTest.py
Labels: area/lintbears, difficulty/low, process/pending review, size/XS

#2296 PySafetyBear.py: Yield correct message template
  bears/python/requirements/PySafetyBear.py
  tests/python/requirements/PySafetyBearTest.py
Labels: area/lintbears, difficulty/low, process/pending review, size/XS
