Repository coala/coala-bears, pull requests merged in 2018-06, with the labels that each got.

#2530 CheckstyleBear: Update download location
  bears/java/CheckstyleBear.py
Labels: area/lintbears, importance/critical, needs backport, size/XS, type/dependencies

#2497 test-requirements.txt: Change the requirement for pip
  test-requirements.txt
Labels: difficulty/newcomer, process/pending review, size/XS, type/bug

#2517 .gitignore: Remove `package-lock.json`
  .gitignore
  package-lock.json
Labels: difficulty/newcomer, importance/low, process/pending review, size/XXL

#2294 bears/general: Add LicenseHeaderBear
  bears/general/LicenseHeaderBear.py
  tests/general/LicenseHeaderBearTest.py
  tests/general/licenseheader_test_files/CopyrightWithoutAuthor.java
  tests/general/licenseheader_test_files/__init__.py
  tests/general/licenseheader_test_files/copyright_with_different_author.txt
  tests/general/licenseheader_test_files/copyright_with_given_author.txt
  tests/general/licenseheader_test_files/no_copyright.py
Labels: bear proposal, difficulty/low, importance/high, importance/low, size/S

#2515 .ci/: export TERM in deps files
  .ci/deps.apt.sh
  .ci/deps.opam.sh
  .ci/deps.pip.sh
  .ci/deps.sh
  .travis.yml
  circle.yml
Labels: area/ci, difficulty/low, importance/medium, size/XS

#2544 CI: Enable pytest-profiling
  setup.cfg
  test-requirements.txt
Labels: size/XS

#2547 .travis.yml: Add apt package aspcud
  .travis.yml
Labels: area/ci, size/XS, type/dependencies

#2550 Moban sync
  .moban.yaml
  netlify.toml
  runtime.txt
  setup.py
Labels: process/pending review, size/XS
