Repository coala/coala-bears, pull requests merged in 2018-05, with the labels that each got.

#2381 RLintBear.py: Add asciinema link
  bears/r/RLintBear.py
Labels: difficulty/newcomer, size/XS

#2454 GitCommitBear: Removed doubled word 'end end'
  bears/vcs/git/GitCommitBear.py
Labels: area/documentation, difficulty/newcomer, size/XS

#2459 GitCommitBear: Refactor issue regexes
  bears/vcs/git/GitCommitBear.py
Labels: area/genericbears, difficulty/low, size/XS

#2122 Linter: SASSLintBear
  bear-requirements.yaml
  bears/scss/SASSLintBear.py
  package.json
  tests/scss/SASSLintBearTest.py
  tests/scss/test_files/sass-lint.yml
Labels: bear proposal, size/S

#2485 setup.py: Sync moban
  setup.py
Labels: size/XS

#2484 CommitBear: Fix regex for issue id
  bears/vcs/CommitBear.py
  tests/vcs/git/GitCommitBearTest.py
Labels: area/genericbears, difficulty/low, importance/medium, size/XS

#2494 .gitignore: Add ignore rule for package-lock.json
  .gitignore
Labels: difficulty/newcomer, size/XS

#2492 InvalidLinkBear.py: Correct broken link message
  bears/general/InvalidLinkBear.py
Labels: difficulty/low, importance/low, size/XS, type/bug
