Repository coala/coala-bears, pull requests merged in 2018-04, with the labels that each got.

#2341 PrettierLintBear.py: Add more tests
  tests/js/PrettierLintBearTest.py
Labels: area/tests, difficulty/low, size/XS

#2255 GNUIndentBear: Add infinite line length
  bears/c_languages/GNUIndentBear.py
  tests/c_languages/GNUIndentBearTest.py
Labels: area/lintbears, difficulty/low, size/XS, type/feature

#2113 Add: Non-mocked test of PySafetyBear
  tests/python/requirements/PySafetyBearWithoutMockTest.py
  tests/python/requirements/PySafety_test_files/requirement.txt
Labels: difficulty/low, size/XS, status/blocked

#2402 .coafile: Replace Default section with all
  .coafile
Labels: difficulty/newcomer, size/XS

#2403 .travis.yml: Skip unsupported on pull requests
  .travis.yml
Labels: size/XS

#2367 QuotesBear.py: Add preferred quote in Result
  bears/general/QuotesBear.py
Labels: area/usability, difficulty/low, importance/medium, size/XS

#2415 Remove rultor
  .ci/check_maintainership.sh
  .ci/deploy.pypi.sh
  .gitignore
  .rultor.yml
Labels: area/ci, difficulty/low, importance/medium, size/XS

#2429 PycodestyleBear: Add default ignore W504
  bears/python/PycodestyleBear.py
Labels: area/ci, difficulty/medium, importance/critical, process/pending review, size/XS, type/codestyle

#2440 PEP8Bear: Add infinite line length
  bears/python/PEP8Bear.py
  tests/python/PEP8BearTest.py
Labels: area/lintbears, difficulty/low, size/XS

#2227 LineCountBear.py: Add min_lines_per_file
  bears/general/LineCountBear.py
  tests/general/LineCountBearTest.py
Labels: area/newsettings, difficulty/low, size/S

#2438 PrettierLintBear.py: Add CAN_FIX metadata
  bears/js/PrettierLintBear.py
Labels: area/aspects, difficulty/low, importance/medium, size/XS

#2414 PrettierLintBear.py: Fix syntax error regex
  bears/js/PrettierLintBear.py
  tests/js/PrettierLintBearTest.py
Labels: area/lintbears, difficulty/low, process/pending review, size/XS, type/bug

#2334 RadonBear.py: Change bears settings
  bears/python/RadonBear.py
  tests/python/RadonBearTest.py
Labels: difficulty/low, hacktoberfest, importance/high, importance/medium, process/pending review, size/XS

#2200 KeywordBearTest.py: Add test for multiple patches
  tests/general/KeywordBearTest.py
Labels: area/genericbears, area/tests, difficulty/low, size/XS, type/test

#2439 XMLBear.py: Add CAN_FIX metadata
  bears/xml2/XMLBear.py
Labels: area/aspects, difficulty/low, importance/medium, process/pending review, size/XS

#2189 Revert ".travis.yml: Use Python 3.6.1"
  .travis.yml
Labels: size/XS

#2235 RubySecurityBear.py: Add brakeman
  Gemfile
  bear-requirements.yaml
  bears/ruby/RubySecurityBear.py
  tests/ruby/RubySecurityBearTest.py
  tests/ruby/brakeman_test_files/app/models/account.rb
  tests/ruby/brakeman_test_files/app/models/user.rb
Labels: area/lintbears, bear proposal, size/S

#2451 .ci/deps.opam.sh: Fix uncached opam dependencies
  .ci/deps.opam.sh
Labels: difficulty/medium, size/XS

#2314 DockerfileLintBear: Update bear
  bear-requirements.yaml
  bears/configfiles/DockerfileLintBear.py
  package.json
  tests/configfiles/DockerfileLintBearTest.py
  tests/configfiles/dockerfile_lint_test_files/sample_rule.yaml
Labels: area/lintbears, difficulty/low, process/pending review, size/XS

#2455 GitCommitBear: parse remote with giturlparse
  bear-requirements.txt
  bear-requirements.yaml
  bears/vcs/git/GitCommitBear.py
Labels: area/ci, difficulty/medium, importance/low, size/XS, status/blocked, type/dependencies
