Repository coala/coala-bears, pull requests merged in 2019-02, with the labels that each got.

#2848 CI: Fix Pycodestyle warning W605
  bears/c_languages/codeclone_detection/ClangCountingConditions.py
  bears/vcs/git/GitCommitBear.py
Labels: difficulty/medium, importance/high, process/pending review, size/XS, type/bug

#2850 .travis.yml: Update Golang version to 1.11.5
  .travis.yml
Labels: area/ci, difficulty/medium, importance/critical, importance/high, process/pending review, size/XS, type/dependencies

#2852 TextLintBearTest.py: Fix assertion typo
  tests/general/TextLintBearTest.py
Labels: difficulty/newcomer, importance/high, process/pending review, size/XS, type/dependencies

#2837 PySafetyBear.py: Adds Asciinema for PySafetyBear.
  bears/python/requirements/PySafetyBear.py
Labels: area/documentation, difficulty/newcomer, process/pending review, size/XS

#2614 .moban.yaml: Add CI check scripts
  .ci/check_setuptools.py
  .ci/check_unsupported.sh
  .moban.yaml
  .travis.yml
Labels: area/ci, difficulty/low, importance/high, process/pending review, size/XS, status/blocked, type/dependencies

#2856 .travis.yml: Remove use of check_setuptools.py
  .travis.yml
Labels: process/pending review, size/XS

#2860 PySafetyBear.py: Add proxy positional argument
  bears/python/requirements/PySafetyBear.py
  tests/python/requirements/PySafetyBearTest.py
Labels: difficulty/low, importance/high, process/pending review, size/XS, type/dependencies

#2859 RELEASE_NOTES.rst: Fix broken bear API changes URL
  RELEASE_NOTES.rst
Labels: area/documentation, difficulty/low, importance/low, process/pending review, size/S

#2845 LineContinuationBear: Disable if `from` in doctest
  bears/general/LineContinuationBear.py
  tests/general/LineContinuationBearTest.py
Labels: area/documentation, difficulty/medium, importance/medium, process/pending review, size/XS

#2868 LineContinuationBearTest.py: Escape backslash
  tests/general/LineContinuationBearTest.py
Labels: area/tests, difficulty/low, importance/critical, size/XS, type/bug

#2865 moban: Sync from moban templates
  setup.cfg
  test-requirements.txt
Labels: area/ci, difficulty/low, importance/medium, process/pending review, size/XS, type/dependencies

#2867 GitRevertInspectBear: Add asciinema
  bears/vcs/git/GitRevertInspectBear.py
Labels: area/documentation, difficulty/newcomer, process/pending review, size/XS

#2872 Support git-url-parse version 1.2
  bear-requirements.txt
  bear-requirements.yaml
  bears/vcs/CommitBear.py
Labels: area/ci, size/XS

#2842 LanguageToolBearTest.py: Remove SkipTest warning
  tests/natural_language/LanguageToolBearTest.py
Labels: area/tests, size/XS

#2814 reSTLintBear.py: Change rst_lint version
  bear-requirements.txt
  bear-requirements.yaml
  bears/rest/reSTLintBear.py
Labels: area/newsettings, difficulty/low, hacktoberfest, size/XS

#2878 vcs/git: Add GitIgnoreBear
  bears/vcs/git/GitIgnoreBear.py
  tests/vcs/git/GitIgnoreBearTest.py
Labels: bear proposal, size/S
